apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: vamsi  
  labels:
    app: doe_backend
spec:
  selector:
    matchLabels:
      app: doe_backend
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: doe_backend
    spec:
      containers:
      - name: backend
        image: doeapp.azurecr.io/backend1:162
        imagePullPolicy: "IfNotPresent"        
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: vamsi  
  labels:
    app: doe_backend
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: backend
  selector:
    app: doe_backend
  type: ClusterIP
